<?php
session_start();

$dbServerName = "localhost";
$dbUserName = "root";
$dbPassword = '';
$dbName = "uni";

if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $courseID = $_POST['CourseID'];
    $materialID = $_POST['Material'];
    $facultyID = $_POST['facultyID'];
    $title = $_POST['title'];
    $link = $_POST['link'];
    $format = $_POST['format'];

    $connection = new mysqli($dbServerName, $dbUserName, $dbPassword, $dbName);

    if ($connection->connect_error) {
        die("Connection failed: " . $connection->connect_error);
    }

    // Check if the courseID is valid
    $courseCheckQuery = "SELECT * FROM course WHERE courseID = '$courseID'";
    $courseCheckResult = $connection->query($courseCheckQuery);

    if ($courseCheckResult->num_rows == 0) {
        echo '<html>';
        echo '<head>';
        echo '<meta charset="UTF-8">';
        echo '<meta http-equiv="X-UA-Compatible" content="IE-edge">';
        echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
        echo '<title>Error</title>';
        echo '<style>';
        echo 'body {';
        echo '    font-family: Arial, sans-serif;';
        echo '    background-color: #b6dbe2;';
        echo '    margin: 0;';
        echo '    padding: 0;';
        echo '}';
        echo '.container {';
        echo '    display: flex;';
        echo '    flex-direction: column;';
        echo '    align-items: center;';
        echo '    justify-content: center;';
        echo '    height: 100vh;';
        echo '}';
        echo '.content {';
        echo '    text-align: center;';
        echo '    background-color: #fffdeb;';
        echo '    color: #3e3e3c;';
        echo '    padding: 40px;';
        echo '    border-radius: 10px;';
        echo '    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);';
        echo '    margin: 40px;';
        echo '}';
        echo '.content h3 {';
        echo '    font-size: 47px;';
        echo '}';
        echo '.content p {';
        echo '    font-size: 18px;';
        echo '    margin: 10px;';
        echo '}';
        echo '.home-link {';
        echo '    position: absolute;';
        echo '    top: -15px;';
        echo '    left: -10px;';
        echo '    padding: 15px 30px;';
        echo '    background-color: #36454f;';
        echo '    color: #fff;';
        echo '    border-radius: 10px;';
        echo '    font-weight: bold;';
        echo '    font-size: 24px;';
        echo '    text-decoration: none;';
        echo '    margin: 20px;';
        echo '}';
        echo '.home-link:hover {';
        echo '    background-color: #000;';
        echo '}';
        echo '</style>';
        echo '</head>';
        echo '<body>';
        echo '<a class="home-link" href="http://localhost/University/System/Users/Instructor/instructor.php">Home</a>';
        echo '<div class="container">';
        echo '<div class="content">';
        echo '<h3>Error</h3>';
        echo '<p>Invalid Course ID. Please check the course ID and try again.</p>';
        echo '</div>';
        echo '</div>';
        echo '</body>';
        echo '</html>';
    } else {
        // Check if the facultyID is valid
        $facultyCheckQuery = "SELECT * FROM instructor WHERE facultyID = '$facultyID'";
        $facultyCheckResult = $connection->query($facultyCheckQuery);

        if ($facultyCheckResult->num_rows == 0) {
            echo '<html>';
            echo '<head>';
            echo '<meta charset="UTF-8">';
            echo '<meta http-equiv="X-UA-Compatible" content="IE-edge">';
            echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
            echo '<title>Error</title>';
            echo '<style>';
            echo 'body {';
            echo '    font-family: Arial, sans-serif;';
            echo '    background-color: #b6dbe2;';
            echo '    margin: 0;';
            echo '    padding: 0;';
            echo '}';
            echo '.container {';
            echo '    display: flex;';
            echo '    flex-direction: column;';
            echo '    align-items: center;';
            echo '    justify-content: center;';
            echo '    height: 100vh;';
            echo '}';
            echo '.content {';
            echo '    text-align: center;';
            echo '    background-color: #fffdeb;';
            echo '    color: #3e3e3c;';
            echo '    padding: 40px;';
            echo '    border-radius: 10px;';
            echo '    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);';
            echo '    margin: 40px;';
            echo '}';
            echo '.content h3 {';
            echo '    font-size: 47px;';
            echo '}';
            echo '.content p {';
            echo '    font-size: 18px;';
            echo '    margin: 10px;';
            echo '}';
            echo '.home-link {';
            echo '    position: absolute;';
            echo '    top: -15px;';
            echo '    left: -10px;';
            echo '    padding: 15px 30px;';
            echo '    background-color: #36454f;';
            echo '    color: #fff;';
            echo '    border-radius: 10px;';
            echo '    font-weight: bold;';
            echo '    font-size: 24px;';
            echo '    text-decoration: none;';
            echo '    margin: 20px;';
            echo '}';
            echo '.home-link:hover {';
            echo '    background-color: #000;';
            echo '}';
            echo '</style>';
            echo '</head>';
            echo '<body>';
            echo '<a class="home-link" href="http://localhost/University/System/Users/Instructor/instructor.php">Home</a>';
            echo '<div class="container">';
            echo '<div class="content">';
            echo '<h3>Error</h3>';
            echo '<p>Invalid Faculty ID. Please check the faculty ID and try again.</p>';
            echo '</div>';
            echo '</div>';
            echo '</body>';
            echo '</html>';
        } else {
            // Both courseID and facultyID are valid, so insert the course material
            $query = "UPDATE coursematerial SET title = '$title', link = '$link', format = '$format' WHERE courseID = '$courseID' AND materialID = '$materialID' AND facultyID = '$facultyID'";

            
            if ($connection->query($query) === TRUE) {
                echo '<html>';
                echo '<head>';
                echo '<meta charset="UTF-8">';
                echo '<meta http-equiv="X-UA-Compatible" content="IE-edge">';
                echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
                echo '<title>Course Material Added</title>';
                echo '<style>';
                echo 'body {';
                echo '    font-family: Arial, sans-serif;';
                echo '    background-color: #b6dbe2;';
                echo '    margin: 0;';
                echo '    padding: 0;';
                echo '}';
                echo '.container {';
                echo '    display: flex;';
                echo '    flex-direction: column;';
                echo '    align-items: center;';
                echo '    justify-content: center;';
                echo '    height: 100vh;';
                echo '}';
                echo '.content {';
                echo '    text-align: center;';
                echo '    background-color: #fffdeb;';
                echo '    color: #3e3e3c;';
                echo '    padding: 40px;';
                echo '    border-radius: 10px;';
                echo '    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);';
                echo '    margin: 40px;';
                echo '}';
                echo '.content h3 {';
                echo '    font-size: 47px;';
                echo '}';
                echo '.content p {';
                echo '    font-size: 18px;';
                echo '    margin: 10px;';
                echo '}';
                echo '.home-link {';
                echo '    position: absolute;';
                echo '    top: -15px;';
                echo '    left: -10px;';
                echo '    padding: 15px 30px;';
                echo '    background-color: #36454f;';
                echo '    color: #fff;';
                echo '    border-radius: 10px;';
                echo '    font-weight: bold;';
                echo '    font-size: 24px;';
                echo '    text-decoration: none;';
                echo '    margin: 20px;';
                echo '}';
                echo '.home-link:hover {';
                echo '    background-color: #000;';
                echo '}';
                echo '</style>';
                echo '</head>';
                echo '<body>';
                echo '<a class="home-link" href="http://localhost/University/System/Users/Instructor/instructor.php">Home</a>';
                echo '<div class="container">';
                echo '<div class="content">';
                echo '<h3>Course Material Added</h3>';
                echo '<p>Course material added successfully!</p>';
                echo '</div>';
                echo '</div>';
                echo '</body>';
                echo '</html>';
            } else {
                echo '<html>';
                echo '<head>';
                echo '<meta charset="UTF-8">';
                echo '<meta http-equiv="X-UA-Compatible" content="IE-edge">';
                echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
                echo '<title>Error</title>';
                echo '<style>';
                echo 'body {';
                echo '    font-family: Arial, sans-serif;';
                echo '    background-color: #b6dbe2;';
                echo '    margin: 0;';
                echo '    padding: 0;';
                echo '}';
                echo '.container {';
                echo '    display: flex;';
                echo '    flex-direction: column;';
                echo '    align-items: center;';
                echo '    justify-content: center;';
                echo '    height: 100vh;';
                echo '}';
                echo '.content {';
                echo '    text-align: center;';
                echo '    background-color: #fffdeb;';
                echo '    color: #3e3e3c;';
                echo '    padding: 40px;';
                echo '    border-radius: 10px;';
                echo '    box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);';
                echo '    margin: 40px;';
                echo '}';
                echo '.content h3 {';
                echo '    font-size: 47px;';
                echo '}';
                echo '.content p {';
                echo '    font-size: 18px;';
                echo '    margin: 10px;';
                echo '}';
                echo '.home-link {';
                echo '    position: absolute;';
                echo '    top: -15px;';
                echo '    left: -10px;';
                echo '    padding: 15px 30px;';
                echo '    background-color: #36454f;';
                echo '    color: #fff;';
                echo '    border-radius: 10px;';
                echo '    font-weight: bold;';
                echo '    font-size: 24px;';
                echo '    text-decoration: none;';
                echo '    margin: 20px;';
                echo '}';
                echo '.home-link:hover {';
                echo '    background-color: #000;';
                echo '}';
                echo '</style>';
                echo '</head>';
                echo '<body>';
                echo '<a class="home-link" href="http://localhost/University/System/Users/Instructor/instructor.php">Home</a>';
                echo '<div class="container">';
                echo '<div class="content">';
                echo '<h3>Error</h3>';
                echo '<p>Error: ' . $query . '<br>' . $connection->error . '</p>';
                echo '</div>';
                echo '</div>';
                echo '</body>';
                echo '</html>';
            }
        }
    }

    $connection->close();
}
?>
